package handlers

type ResFail struct {
	ErrCode int    `json:"errCode"`
	Message string `json:"message"`
}

const (
	SUCCESS = 0

	//SignUp api 처리 시 발생 에러
	ERR_SIGN_UP_REQUEST_BINDING = 10000 // SignUp 데이터 바인딩 에러
	ERR_SIGN_UP_DUPLICATED_ID   = 10001 // 중복된 Username
	ERR_SIGN_UP_NULL_PASSWORD   = 10002 // 빈 Password
	ERR_SIGN_UP_GET_DB          = 10003 // DB Conn 실패

	// Login api 처리 시 발생 에러
	ERR_LOGIN_REQUEST_BINDING    = 10100
	ERR_LOGIN_INCORRECT_PASSWORD = 10101
	ERR_LOGIN_GET_DB             = 10102
	ERR_LOGIN_CREATE_ACCESSTOKEN = 10103
	ERR_LOGIN_UPDATE_DB          = 10104

	// Logout api 처리 시 발생 에러
	ERR_LOGOUT_REQEUST_BINDING     = 10200
	ERR_LOGOUT_INVALID_ACCESSTOKEN = 10201
	ERR_LOGOUT_GET_DB              = 10202
	ERR_LOGOUT_DELETE_DB           = 10203

	// LoadPlatformsList api 처리 시 발생 에러
	ERR_LOAD_PLATFORMS_LIST_GET_DB    = 10300
	ERR_LOAD_PLATFORMS_LIST_SELECT_DB = 10301

	// LoadPlatformDetail api 처리 시 발생 에러
	ERR_LOAD_PLATFORM_DETAIL_REQUEST_BINDING = 10400
	ERR_LOAD_PLATFORM_DETAIL_GET_DB          = 10401
	ERR_LOAD_PLATFORM_DETAIL_SELECT_DB       = 10402

	// LoadPersonalData api 처리 시 발생 에러
	ERR_LOAD_PERSONAL_DATA_REQUEST_BINDING     = 10500
	ERR_LOAD_PERSONAL_DATA_INVALID_ACCESSTOKEN = 10501
	ERR_LOAD_PERSONAL_DATA_GET_DB              = 10502
	ERR_LOAD_PERSONAL_DATA_SELECT_DB           = 10503

	// LoadSubscribingData api 처리 시 발생 에러
	ERR_LOAD_SUBSCRIBING_DATA_REQUEST_BINDING     = 10600
	ERR_LOAD_SUBSCRIBING_DATA_INVALID_ACCESSTOKEN = 10601
	ERR_LOAD_SUBSCRIBING_DATA_GET_DB              = 10602
	ERR_LOAD_SUBSCRIBING_DATA_SELECT_DB           = 10603

	// RequestPay api 처리 시 발생 에러
	ERR_REQUEST_PAY_REQUEST_BINDING     = 10700
	ERR_REQUEST_PAY_INVALID_ACCESSTOKEN = 10701

	// RequestCancel api 처리 시 발생 에러
	ERR_REQUEST_CANCEL_REQUEST_BINDING     = 10800
	ERR_REQUEST_CANCEL_INVALID_ACCESSTOKEN = 10801
)
